### ISSUE TITLE
[Bug] Error on executing send_command method

### ISSUE THREAD

**Issue by SriramPandikasala** [silverbucket/node-redis-connection-pool#71]
---
name: "🐞 Bug Report"
about: "send_command method"
title: "[Bug] Error on executing send_command method"
labels: "Type: Bug"

---

# **🐞 Bug Report**

## **Describe the bug**

The following error is getting thrown on executing any redis command through the send_command.

```
               res = yield client[funcName](key, val);
                                            ^

TypeError: client[funcName] is not a function
    at RedisConnectionPool.<anonymous> (d:\Sri\Coding\OpenSource\node-redis-connection-pool\dist\index.js:429:45)
    at Generator.next (<anonymous>)
    at fulfilled (d:\Sri\Coding\OpenSource\node-redis-connection-pool\dist\index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### **To Reproduce**

* After initialising redispool ( <code>redisPoolObj.init()</code> ),  the following code was added for which the aforementioned error was thrown

```
redisPoolObj.send_command('HSET', ['firstRedisKey', 'key1', 'Hello, Redis']).then(resp => {
    console.log(resp)
});
```

*  The same error is getting thrown for other commands like HMGET, HGET, etc.

---

### **Expected behaviour**

* It should get executed as per the command provided and not throw any error

---

### **Your environment**

* OS: Windows 10
* Node version: 16.15
* Npm version: 8.5.5
* Redis version: 7.0.2 (Docker)

**Comment by SriramPandikasala** [comment]
I would also like to share my findings and also a probable fix for the same. Could you please guide how I should proceed further?

**Comment by SriramPandikasala** [comment]
I have raised a draft PR for the same to share my suggestion. #72
